export const GET_LEAD_REQUEST = "GET_LEAD_REQUEST";
export const GET_LEAD_SUCCESS = "GET_LEAD_SUCCESS";
export const GET_LEAD_FAIL = "GET_LEAD_FAIL";

export const POST_LEAD_REQUEST = "POST_LEAD_REQUEST";
export const POST_LEAD_SUCCESS = "POST_LEAD_SUCCESS";
export const POST_LEAD_FAIL = "POST_LEAD_FAIL";

export const UPDATE_LEAD_REQUEST = "UPDATE_LEAD_REQUEST";
export const UPDATE_LEAD_SUCCESS = "UPDATE_LEAD_SUCCESS";
export const UPDATE_LEAD_FAIL = "UPDATE_LEAD_FAIL";

export const DELETE_LEAD_REQUEST = "DELETE_LEAD_REQUEST";
export const DELETE_LEAD_SUCCESS = "DELETE_LEAD_SUCCESS";
export const DELETE_LEAD_FAIL = "DELETE_LEAD_FAIL";
