export const TOGGLE_ADD_LEAD_MODAL = "TOGGLE_ADD_LEAD_MODAL";
export const TOGGLE_UPDATE_LEAD_MODAL = "TOGGLE_UPDATE_LEAD_MODAL";
export const TOGGLE_DELETE_LEAD_MODAL = "TOGGLE_DELETE_LEAD_MODAL";
export const RESET_MODAL = "RESET_MODAL"